### PR TITLE
RLI pipeline with documentation 

### PR DESCRIPTION
**Pull request by jupinator**
This routine has validation errors due to regex, the other errors (fields in .yml files, metadata) have been resolved
image

### CODE REVIEW

**Comment by JoryGriffith** [comment]
Hi Luis, 

Here are my comments: 
The output right now is just a plot but it should also be output it as a csv file that can be downloaded
1. Can you add a title to the plot?
2. The plot right now is a bit misleading because the intervals on the years used are inconsistent, is there a way to improve the spacing on the y axis to reflect the fact that the time intervals are different? Maybe don't include every year from 1900 but put a … on the line or something to show time has passed
3. When selecting taxonomic groups can you make it look a bit cleaner in the drop down menu? Like remove the underscores and just re-add them in the R script if you need them for the function
4. It would be great if there was a plot that also plotted RLI for the different groups as different lines (and also output the group-level RLIs as a csv file)
5. Can you add a bit more description of what the values mean for RLI under the plot so users can better understand

Thank you for all your work!

**Comment by JoryGriffith** [comment]
Hi Luis, 
Can we get a status update on this? We are hoping to merge soon.

**Comment by jupinator** [comment]
The output right now is just a plot but it should also be output it as a csv file that can be downloaded DONE

Can you add a title to the plot? DONE

The plot right now is a bit misleading because the intervals on the years used are inconsistent, is there a way to improve the spacing on the y axis to reflect the fact that the time intervals are different? Maybe don't include every year from 1900 but put a … on the line or something to show time has passed DONE

When selecting taxonomic groups can you make it look a bit cleaner in the drop down menu? Like remove the underscores and just re-add them in the R script if you need them for the function 
This are the names in the UICN API

It would be great if there was a plot that also plotted RLI for the different groups as different lines (and also output the group-level RLIs as a csv file) no, this is not possible in this current version  

Can you add a bit more description of what the values mean for RLI under the plot so users can better understand  I put the link to the documentation but this link must be replaced in the final version of the pipe

**Review by jmlord — APPROVED** [review]
I'm merging this to a staging branch to check the action from our repo. Otherwise, Jory had already validated the bulk of it, it should be in main today.

**Pull request merged**
