### PR TITLE
Merge SHI branch with additions from previous pull request

### PR DESCRIPTION
**Pull request by MaIsAp**
This branch has a first version of the pipelines for the SHI and SHS using Global Forest Watch data and has fixed the issues with the region and a different starting year than 2000.

Original pull request: https://github.com/GEO-BON/bon-in-a-box-pipelines/pull/101

### CODE REVIEW

**Comment by jmlord** [comment]
SHI examples should have more than one species. Currently it's the default from the script, 1 species, hence doing an SHI.

**Comment by MaIsAp** [comment]
> SHI examples should have more than one species. Currently it's the default from the script, 1 species, hence doing an SHS.

It should had Saguinus oedipus and Ateles fusciceps for the SHI option

**Comment by jmlord** [comment]
Sorry, I changed sanguinus to "Oedipomidas oedipus". It has been renamed in IUCN database.

**Comment by MaIsAp** [comment]
> Sorry, I now changed sanguinus to "Oedipomidas oedipus" in above defaults. It has been renamed in IUCN database.

That is perfect, thanks!

**Comment by jmlord** [comment]
Hmmm... not found in range maps, so now I have put this: 

Myrmecophaga tridactyla, Ateles fusciceps

And ran it to completion!

**Comment by MaIsAp** [comment]
> Hmmm... not found in range maps, so now I have put this:
> 
> Myrmecophaga tridactyla, Ateles fusciceps
> 
> And ran it to completion!

Sorry, the only thing that I think is missing is that if I am not mistaken they had different forest ranges, but I do not have access to it right now.
Now you make me think if the SHS is working fully with Oedipomidas when trying to use Guillaume's function to download the range maps, because those might have the "old" taxonomy.

**Comment by jmlord** [comment]
> when trying to use Guillaume's function to download the range maps, because those might have the "old" taxonomy.

Yes, we need to auto-update these files. @glaroc  can that be put on a cron job?

>  if I am not mistaken they had different forest ranges

Ok, please adjust this when you can.

**Comment by JoryGriffith** [comment]
One thing that needs to be fixed is the output in the viewer - the map of habitat change should be categorical but is showing up as numeric (see issue https://github.com/GEO-BON/bon-in-a-box-pipeline-engine/issues/89)

**Review by JoryGriffith — APPROVED** [review]
Good job, yay finally!

**Pull request merged**
